export const regions = {
  EAST_ASIA: 'EAST ASIA',
  SOUTH_ASIA: 'SOUTH ASIA',
  MIDDLE_EAST: 'MIDDLE EAST',
  EUROPE: 'EUROPE',
  NORTH_AMERICA: 'NORTH AMERICA',
  AFRICA: 'AFRICA',
  LATIN_AMERICA: 'LATIN AMERICA',
}
